### ISSUE TITLE
Allow a jQuery element to be passed

### ISSUE THREAD

**Issue by ccummings** [canjs/can-view-model#21]
It's quite common, especially in projects migrating from 2.3, to pass a jQuery-wrapped element to `viewModel`. Right now this will return a new `DefaultMap` and not the viewModel that is attached to the underlying DOM node.

I propose that If the element passed into `viewModel` is an Array, `viewModel` take the first element of the Array and use that.

**Comment by cherifGsoul** [comment]
marged and realesed
