### ISSUE TITLE
Error thrown when canViewModel called on select with no options

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-view-model#31]
https://jsbin.com/yurevuniga/1/edit?html,js,output

Due to the jquery-like support added in can-view-model 3.2.0, there is an isArrayLike check performed on the element when deciding how to handle it (since it may be an array).  isArrayLike checks for a length property (which select elements have) and whether the last index (length - 1) exists as a property if the length is greater than 0.  In the case of selects, there is a length property but numeric indexes are not available, so this usually fails, but if the select has zero length, it will be treated as an array-like and unboxed to its first element, which is undefined.

Note that this is a generic error as well, as any zero-length jQuery will return undefined for [0] and cause an error to be thrown.

Recommend: use `el instanceof Node` or `el.nodeType` to test whether `el` is a node before doing array unboxing on it; also consider returning `undefined` if `el` is undefined/null after the initial type processing.

**Comment by andrejewski** [comment]
Relevant line: https://github.com/canjs/can-view-model/blob/04d8381733c882548bdac4e511edf68259a61637/can-view-model.js#L13
