### ISSUE TITLE
Cannot set custom Map on element

### ISSUE THREAD

**Issue by ccummings** [canjs/can-view-model#5]
You cannot set a custom `can-map` or `can-define/map` on an element using `can-view-model`.

```js
const customMap = canMap.extend({});
canViewModel(document.getElementById('demo'), new customMap({ name: 'foo' }));

const customDMap = DfineMap.extend({});
canViewModel(document.getElementById('demo'), new customDMap({ name: 'foo' }));
```

Neither of these will yield what you'd expect. Depending on the environment you'll get an instance of `types.DefaultMap` (could be canMap or DefineMap) or `SimpleMap`.

Ideally there would be a check before [this](https://github.com/canjs/can-view-model/blob/master/can-view-model.js#L11) line to determine of the thing being passed in is map-like

**Comment by justinbmeyer** [comment]
Why do you need to set one?

Currently, you can use `domData.set.call( el, "viewModel", VM)`.  

But yeah, I think is is a fine change.

**Comment by cherifGsoul** [comment]
@justinbmeyer I made a branch for this issue https://github.com/canjs/can-view-model/blob/set-custom-Map-on-element/can-view-model.js#L12 it works for SimpleMap for now Im looking how I can handle other map types.

**Comment by cherifGsoul** [comment]
merged and realesed
