### ISSUE TITLE
Using view model with array-like elements should be documented

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-view-model#53]
Using ```can-view-model``` with array-like elements (eg: jquery) is not documented, here https://canjs.com/doc/can-view-model.html#Use the docs should explain that this kind of elements can be passed.

**Comment by phillipskevin** [comment]
This was added in https://github.com/canjs/can-view-model/commit/8156f3a66ac373720aa1b01d2dc2553ffa844d5e. Just needs to be published. cc @bmomberger-bitovi.

**Comment by bmomberger-bitovi** [comment]
New minor release with the documentation changes: https://github.com/canjs/can-view-model/releases/tag/v3.5.0 - @phillipskevin please add to CanJS 3.11.0.

**Comment by phillipskevin** [comment]
This is added to `minor`.
